ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "CausalCodeCapability"
  site-url: "https://WM-SEMERU.github.io/CausalCodeCapability"
  description: "Code Syntax Concept Library for Neural Code Models Interpretability"
  twitter-card: true
  open-graph: true
  repo-branch: master
  repo-url: "https://github.com/WM-SEMERU/CausalCodeCapability"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/WM-SEMERU/CausalCodeCapability"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
