# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/CausalCodeCapability',
                'doc_host': 'https://WM-SEMERU.github.io',
                'git_url': 'https://github.com/WM-SEMERU/CausalCodeCapability',
                'lib_path': 'CausalCodeCapability'},
  'syms': {'CausalCodeCapability.core': {'CausalCodeCapability.core.foo': ('core.html#foo', 'CausalCodeCapability/core.py')}}}