# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/CausalCodeCapability',
                'doc_host': 'https://WM-SEMERU.github.io',
                'git_url': 'https://github.com/WM-SEMERU/CausalCodeCapability',
                'lib_path': 'CodeSyntaxConcept'},
  'syms': { 'CodeSyntaxConcept.core.aligners.custom_aligner': {},
            'CodeSyntaxConcept.core.aligners.needleman_wunch': {},
            'CodeSyntaxConcept.core.data.testset_splitter': {},
            'CodeSyntaxConcept.core.mappers.concept_mapper': {},
            'CodeSyntaxConcept.core.parsers.ast_unparser': {},
            'CodeSyntaxConcept.core.parsers.tree_sitter_unparser': {}}}