# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/CodeSyntaxConcept',
                'doc_host': 'https://WM-SEMERU.github.io',
                'git_url': 'https://github.com/WM-SEMERU/CodeSyntaxConcept',
                'lib_path': 'CodeSyntaxConcept'},
  'syms': {'CodeSyntaxConcept.core.data.code_search_net': {}, 'CodeSyntaxConcept.core.parsers.tree_sitter_parser': {}}}